E_Learning/E_Learning/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('stuff/', include('home.urls')),
    path('',include('accounts.urls')),
]

E_Learning/home/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.views.generic import TemplateView
app_name = "home"

urlpatterns = [
    path(r'add_notes/', views.add_notes, name="add_notes"),
    path(r'view_notes/', views.view_notes, name="view_notes"),
    path(r'add_club/', views.add_club, name="add_club"),
    path('display_clubs/', views.display_clubs, name='display_clubs'),
    path('addbook/',views.addbook,name='addbook'),
    path('displaybook/',views.displaybook,name='displaybook'),
    path('(?P<username>[\w.@+-]+)/(?P<book_title>[\w.@+-]+)/(?P<status>[\w.@+-]+)/requestbook/',views.requestbook, name='requestbook'),
    path('view_requests/',views.view_requests, name='view_requests'),
    path('(?P<book_title>[\w.@+-]+)/(?P<req_id>[\w.@+-]+)/(?P<req_user>[\w.@+-]+)/(?P<username>[\w.@+-]+)/updatet/', views.updatet,name='updatet'),
    path('(?P<book_title>[\w.@+-]+)/(?P<req_id>[\w.@+-]+)/(?P<req_user>[\w.@+-]+)/(?P<username>[\w.@+-]+)/updatef/', views.updatef,name='updatef'),
    path('notifications/',views.notifications,name='notifications'),
    path('notifications/delete/(?P<n_id>[\w.@+-]+)/',views.n_delete,name='n_delete'),
    path('chatrooms/',views.allchat,name='allchat'),
    path('chatroom/(?P<self>[\w.@+-]+)/(?P<other>[\w.@+-]+)/',views.chatroom,name='chatroom'),
    
    
    path('addcourse/',views.addcourse,name='addcourse'),
    path('course_list/',views.course_list,name='course_list'),
    path('addextcourse/',views.addexternalcourse,name='addextcourse'),
    path('extcourse_list/',views.external_course_list,name='extcourse_list'),
    re_path(r'(?P<coursename>[\w.@+-]+)/(?P<videoname>[\w.@+-]+)/',views.viewcourse),
    path('courses/',TemplateView.as_view(template_name='home/courses.html')),
    path('books/',TemplateView.as_view(template_name='home/books.html')),
    path('notes/',TemplateView.as_view(template_name='home/notes.html')),
    path('requests/',TemplateView.as_view(template_name='home/request.html')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

E_Learning/home/models.py
from django.db import models

# Create your models here.

E_Learning/home/views.py
from django.shortcuts import render,redirect
from pyrebase import pyrebase
from django.contrib import auth
from functions import *
from decorators import *
import operator


config = {
    "apiKey": "AIzaSyAEue4ktaLv-1wqKQgtgkfWJ1Oj6NNW-8U",
    "authDomain": "e-learning-ccbd8.firebaseapp.com",
    "databaseURL": "https://e-learning-ccbd8.firebaseio.com",
    "projectId": "e-learning-ccbd8",
    "storageBucket": "e-learning-ccbd8.appspot.com",
    "messagingSenderId": "1053587965345",
    "appId": "1:1053587965345:web:b97bb311c911183b0d77e0",
    "measurementId": "G-K1YGG2H5VQ"
}

firebase = pyrebase.initialize_app(config)
authe = firebase.auth()
database = firebase.database()

def dashboard(request):
    return render(request, "accounts/dashboard.html")


@login_required

def add_notes(request):
    if request.method == 'GET':
        return render(request, "home/add_notes.html")

    else:
        notes_name = request.POST.get('notes_name')
        url = request.POST.get('url')
        upload = request.FILES.get('url')
        # print(upload)
        try:
            # snatchout id from sessions
            idtoken = request.session['uid']
            a = authe.get_account_info(idtoken)
            a = a['users']
            a = a[0]
            a = a['localId']
            # a contains local id
        except:
            return render(request, "accounts/login.html")

        storage = firebase.storage()            # important

        storage_path = "notes/" + notes_name + ".pdf"
        # print(storage_path)
        storage.child(storage_path).put(upload, idtoken)
        url = storage.child(storage_path).get_url(idtoken)



        username = database.child("users").child(a).child("details").child("username").get(idtoken).val()
        tags = database.child("users").child(a).child("details").child("admin").get(idtoken).val()
#         # print(username)
        data = {
            "tags": tags,
            "url": url,
            "username": username,
            "approved": 0,
        }

        database.child('Notes').child(notes_name).set(data, idtoken)
        return render(request, "home/notes.html")


@login_required
def view_notes(request):
    notes = database.child('Notes').shallow().get().val() #returns dictionary => convert to list
    # print(notes)
    list_notes = [*notes]
    # print(list_notes)
    tags = []
    urls = []
    usernames = []
    approved = []
    for i in list_notes:
        tag = database.child('Notes').child(i).child('tags').get().val()
        tags.append(tag)
        url = database.child('Notes').child(i).child('url').get().val()
        urls.append(url)
        username = database.child('Notes').child(i).child('username').get().val()
        usernames.append(username)
        approve = database.child('Notes').child(i).child('approved').get().val()
        approved.append(approve)

    # print(tags)
    # print(urls)
    # print(usernames)
    combine_list = zip(list_notes,tags,usernames,urls,approved)
    return render(request, "home/display_notes.html", {'combine_list':combine_list})

@login_required
def add_club(request):
        if request.method == 'GET':
            return render(request, "home/add_club.html")

        else:
            # print("falak")
            url = request.POST.get('url')
            # print(url)
            upload = request.FILES.get('url')
            # print(upload)

            try:
                idtoken = request.session['uid']
                a = authe.get_account_info(idtoken)
                a = a['users']
                a = a[0]
                a = a['localId']
                # a contains local id
            except:
                return render(request, "accounts/login.html")

            storage = firebase.storage()

            storage_path = "clubs/" + tags
            storage.child(storage_path).put(upload, idtoken)
            url = storage.child(storage_path).get_url(idtoken)

            username = database.child("users").child(a).child("details").child("username").get(idtoken).val()
            tags = database.child("users").child(a).child("details").child("admin").get(idtoken).val()
#             # print(username)
            data = {
                "url": url,
                "username": username,
                "approved": 0,
            }

            database.child('Clubs').child(tags).set(data, idtoken)
            return render(request, "home/homepage.html")
@login_required
def display_clubs(request):
    clubs = database.child('Clubs').shallow().get().val()
    # print(clubs)
    list_clubs = [*clubs]
    # print(list_clubs)
    urls = []
    usernames = []
    approved = []
    for i in list_clubs:
        url = database.child('Notes').child(i).child('url').get().val()
        urls.append(url)
        username = database.child('Notes').child(i).child('username').get().val()
        usernames.append(username)
        approve = database.child('Notes').child(i).child('approved').get().val()
        approved.append(approve)

    # print(urls)
    # print(usernames)
    combine_list = zip(list_clubs,usernames,urls,approved)
    return render(request, "home/display_clubs.html", {'combine_list':combine_list})
@login_required
def addbook(request):
    if request.method =='GET':
        return render(request,"home/addbook.html")
    else:
        bookname=request.POST.get('book_name')
        url = request.POST.get('url')
        upload = request.FILES.get('url')


        try:
            idtoken=request.session['uid']
            a = authe.get_account_info(idtoken)
            a = a['users']
            a=a[0]
            a=a['localId']
        except:
            return render(request,"accounts/signup.html")

        storage = firebase.storage()
        storage_path = "books/" + bookname + ".pdf"
        storage.child(storage_path).put(upload, idtoken)
        url = storage.child(storage_path).get_url(idtoken)

        username = database.child("users").child(a).child("details").child("username").get(idtoken).val()
        email = database.child("users").child(a).child("details").child("email").get(idtoken).val()
        tags = database.child("users").child(a).child("details").child("admin").get(idtoken).val()
        # print(tags)
        data={
            "tags":tags,
            "username":username,
            "status": 1,
            "email": email,
            "url": url,
            "approved": 0,
        }
        database.child("books").child(bookname).set(data,idtoken)
        return render(request,"home/books.html")


@login_required

def displaybook(request):
    books = database.child('books').shallow().get().val()

    list_books = [*books]

    tags = []
    usernames = []
    status = []
    emails = []
    approved = []
    urls = []
    for i in list_books:
        tag = database.child('books').child(i).child('tags').get().val()
        tags.append(tag)
        username = database.child('books').child(i).child('username').get().val()
        usernames.append(username)
        email = database.child('books').child(i).child('email').get().val()
        emails.append(email)
        url = database.child('books').child(i).child('url').get().val()
        urls.append(url)
        statusz = database.child('books').child(i).child('status').get().val()
        status.append(statusz)
        approve = database.child('books').child(i).child('approved').get().val()
        approved.append(approve)

    # print(approved)
    combine_list = zip(list_books,tags,usernames,status,emails,approved,urls)
    return render(request, "home/display_books.html", {'combine_list':combine_list})





@login_required
def requestbook(request,username,book_title,status):
    try:
        idtoken = request.session['uid']
        a = authe.get_account_info(idtoken)
        a = a['users']
        a = a[0]
        a = a['localId']
    except:
        return render(request, "accounts/signup.html")

    j = database.child('j').get().val()
    if j is None:
        database.child('j').set(0, idtoken)
    j = database.child('j').get().val()
    j = j + 1
    database.child('j').set(j, idtoken)


    req_user = database.child("users").child(a).child("details").child("username").get(idtoken).val()
    data = {
        "owner": username,
        "req_user": req_user,
        "status":status,
        "book_title":book_title,
    }
    database.child("requests").child(j).set(data, idtoken)

    return redirect('home:displaybook')

@login_required   
def addcourse(request):
    if request.method == 'GET':
        return render(request, "home/addcourse.html")

    else:
        # print("falak")
        course_name = request.POST.get('course_name')
        video_name = request.POST.get('video_name')
        tags = request.POST.get('tags')
        upload=request.FILES.get('url')
        # print(upload)


        try:
            idtoken = request.session['uid']
            a = authe.get_account_info(idtoken)
            a = a['users']
            a = a[0]
            a = a['localId']
            # a contains local id
        except:
            return render(request, "accounts/login.html")

        storage = firebase.storage()
        
        storage_path = "videos/"+course_name+"/"+video_name+".mp4"
        storage.child(storage_path).put(upload,idtoken)
        url = storage.child(storage_path).get_url(idtoken)

        username = database.child("users").child(a).child("details").child("username").get(idtoken).val()
#         #print(username)
        data = {
            "tags": tags,
            "url": url,
            "username": username,
        }

        database.child('course').child(course_name).child(video_name).set(data, idtoken)
        return render(request, "home/courses.html")
@login_required
def course_list(request):
    courses = database.child('course').shallow().get().val()
#     # print(courses)
    list_courses = [*courses]
#     # print(list_courses)
    link_lists = []
    for i in list_courses:

E_Learning/home/templates/home/add_notes.html
{% extends "base.html" %}
{% block js %}
{% if error %}
<!--<script>-->
<!--    alert('{{ error }}');-->
<!--</script>-->
{{error}}
{% endif %}
{% endblock %}


{% block main %}
<form method="post" enctype="multipart/form-data"   class="form-control text-center border border-light p-5" >
    {% csrf_token %}
<!--    Uploaded by :-->
<!--    <input type="text" name="username" value="{{user.details.username}}" disabled /><br>-->
    Notes_Title :
    <h6 class ="alert-primary">Do not give spaces or any special character</h6>
    <input type="text" class="form-control mb-4" name="notes_name"  required /><br>




    Upload Notes:

        <input type="file" class="form-control mb-4" name="url" accept=".pdf" >

        <br>


    <input type="submit" class="form-control mb-4" value="publish">
 </form>
<br>
{% endblock %}

E_Learning/home/templates/home/allchat.html
{% extends "base.html" %}
{% block js %}
{% if error %}
<!--<script>-->
<!--    alert('{{ error }}');-->
<!--</script>-->
{{error}}
{% endif %}
{% endblock %}

{% block css %}
<style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 18px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 12px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>
{% endblock %}

{% block main %}
<div class="container">
    <p><h1>Friends:</h1></p>
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for friends.." title="Type in a name">
  <table class="table table-hover" id="myTable">
    <thead>
      <tr class="header">
        <th>Name</th>
        <th>Branch</th>
        <th>Email</th>
          <th>Club</th>
          <th>Year</th>
          <th>Contact</th>
      </tr>
    </thead>
    <tbody>
{% for admin,branch,email,username,year,id in combine_user  %}
      <tr>
           <td>{{username}}</td>
          <td>{{branch}}</td>
          <td>{{email}}</td>
          <td>{{admin}}</td>
          <td>{{year}}</td>
<!--          <td>{{id}}</td>-->
<!--          <td>{{selfid}}</td>-->
          <td><a href="{% url 'home:chatroom' selfid id %}"> Chat</a></td>


      </tr>
{% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}



{% block js2 %}
<script>

function myFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
{% endblock %}

E_Learning/home/templates/home/display_books.html
{% extends "base.html" %}
{% block js %}
{% if error %}
<!--<script>-->
<!--    alert('{{ error }}');-->
<!--</script>-->
{{error}}
{% endif %}
{% endblock %}



{% block css %}

<style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 18px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 12px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>
{% endblock %}

{% block main %}
<div class="container">
    <p><h1>BOOKS:</h1></p>
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for book_title.." title="Type in a name">
  <table class="table table-hover" id="myTable">
    <thead>
      <tr class="header">
        <th>Book_Title</th>
        <th>Tag</th>
        <th>User</th>
          <th>Status</th>
        <th>Available</th>
          <th>Contact</th>
          <th>Request</th>
      </tr>
    </thead>
    <tbody>
{% for list_books,tags,usernames,status,emails,approved,urls in combine_list  %}
      <tr>
          <td>{{list_books}}</td>
           <td>{{tags}}</td>
        <td>{{usernames}}</td>
        <td>{{status}}</td>
          {% if tags != "General"  %}
            <td> <a href = {{urls}}>Download</td>
          {% endif %}
          {% if approved == 0 and tags == "General" %}
            <td>(To be Approved)</td>
         {% endif %}
          {% if approved == 1 and tags == "General" %}
            <td>  <a href = {{urls}}>Download</td>
          {% endif %}
        <td>
            {% if status == 1 %}
                {{emails}}
            {% else %}
                Not Available
            {% endif %}
        </td>
          <td>
            {% if status == 1 %}
              <a href="{% url 'home:requestbook'  usernames list_books status %}"> Request</a>
            {% else %}
                Not Available
            {% endif %}
        </td>

      </tr>
{% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}



{% block js2 %}
<script>

function myFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++)
  {
    td = tr[i].getElementsByTagName("td")[0];
    if (td)
    {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1)
       {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
{% endblock %}

E_Learning/home/templates/home/notifications.html
{% extends "base.html" %}
{% block js %}
{% if error %}
<!--<script>-->
<!--    alert('{{ error }}');-->
<!--</script>-->
{{error}}
{% endif %}
{% endblock %}

{% block css %}
<style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 18px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 12px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>
{% endblock %}

{% block main %}
<div class="container">
    <p><h1>Notifications:</h1></p>
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for notification books.." title="Type in a name">
  <table class="table table-hover" id="myTable">
    <thead>
      <tr class="header">
        <th>Books</th>
        <th>Message</th>
          <th>Delete</th>
      </tr>
    </thead>
    <tbody>
{% for my_reply, users, n_id, mystr,mybooks in combine_list  %}
      <tr>
          <td>{{mybooks}}</td>
           <td>{{mystr}}</td>
        <td><a href="{% url 'home:n_delete' n_id %}">Delete</td>


      </tr>
{% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}



{% block js2 %}
<script>

function myFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
{% endblock %}

E_Learning/home/templates/home/request.html
{% extends "base.html" %}
{% block js %}{% load static %}{% endblock %}
{% block request %}active{% endblock %}
{% block mycss %}
<style>
@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,800,700,300);
@import url(https://fonts.googleapis.com/css?family=Squada+One);
@import url('https://fonts.googleapis.com/css?family=Raleway:800&display=swap');
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
.heading {
font-family: 'Proxima Nova Soft', 'Helvetica Neue', sans-serif;
font-size: 36px;
}
body{
background: #ffffff
}
#logo {
  font-family: 'Raleway', sans-serif;
  color: #ffffff;
  text-decoration: none;
  /*text-transform: uppercase;*/
  font-size: 150px;
  font-weight: 800;
  letter-spacing: -3px;
  line-height: 1;
  text-shadow: #EDEDED 3px 2px 0;
  position: relative;
  margin-top: 0px;
}
.column {
  float: left;
    /*display: block;*/
}
.containers h2 {
  font-size: 20px;
  /*font-weight: bold;*/
  font-family: 'Proxima Nova Soft', 'Helvetica Neue', sans-serif;
}
@media screen and (max-width: 650px) {
  .col-lg-3 {
    width: 100%;
    display: block;
  }
}
.myImg {
  height: 210px;
  width: 216px;
  margin-top: 20px;
}
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2 );
    width: 260px;
   height: 400px;
  margin-bottom: 16px;
  padding: 0 15px;
  margin-left: 10px;
  margin-right: 10px;
  position: relative;
 background: LightGray;  /* fallback for old browsers */
/*background: -webkit-linear-gradient(to bottom, #CFDEF3, #E0EAFC);*/   /*Chrome 10-25, Safari 5.1-6 */
/*background: linear-gradient(to bottom, #CFDEF3, #E0EAFC);*/ /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
border-radius:10px;
}
.containers {
  padding: 0 16px;
}
.containers::after, .row::after {
  content: "";
  clear: both;
  display: table;
}
.title {
  color: grey;
  margin-top: -5px;
  margin-bottom: 20px;
}
.col-lg-3 {
  padding-bottom: 20px;
}
.upper{
   /* The image used */
  background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url("https://media.gettyimages.com/photos/graduation-day-picture-id1066324992?s=612x612");
  /* Full height */
  height: 350px;
  /* Center and scale the image nicely */
  background-attachment: fixed;
  background-position: center;
  background-size: cover;
        /*    height: 40vh;
          background-attachment: fixed;
          background-size: cover;
          margin-top:0;
          padding-top:0; */
}
.mail{
 /* display: inline-block;*/
 /* padding: 8px;*/
  /*text-align: center;*/
/*position: absolute;*/
  margin-right: 10px;
  margin-left: 10px;
  margin-bottom:   0px;
  padding-bottom: 0px;
}
.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  width: 80%;
  position: absolute;
  right: 0px;
  margin-right: 26px;
  margin-left: 26px;
  bottom:   10px;
  /*margin-bottom: 0px !important;*/
}
.button:hover {
  background-color: #555;
}
.row {
  padding-bottom: 30px;
}
.cent{
  display: block;
  margin-left: auto;
  margin-right: auto;
}
</style>
{% endblock %}

{% block main %}
 <center>
<div class="upper image"><h1 id="logo">Handle Requests</h1>
</div>
<br>
<div class="col-lg-1"></div>
<div class="col-lg-10 cent ">
<div class="row">
  <div class="col-lg-3 ">
  </div>

  <div class="col-lg-3 ">
    <div class="card">
      <img class="myImg"  src="{% static 'home/extwebsite.jpg' %}" alt="extcourses" style="width:100%">
      <div class="containers">
        <h2>Requests</h2>
      </div>
      <p><a href="{% url 'home:view_requests' %}"><button class="button">Go</button></a></p>
    </div>
  </div>

  <div class="col-lg-3 ">
    <div class="card">
      <img class="myImg"  src="{% static 'home/online-course-512.png' %}" alt="list" style="width:100%">
      <div class="containers">
        <h2> Notifications </h2>
      </div>
      <p><a href="{% url 'home:notifications' %}"><button class="button">Go</button></a></p>
    </div>
  </div>

  <div class="col-lg-3 ">

  </div>
  
</div>
</div>
</div>
</center>
{% endblock %}

E_Learning/home/templates/home/viewrequests.html
{% extends "base.html" %}
{% block js %}
{% if error %}
<!--<script>-->
<!--    alert('{{ error }}');-->
<!--</script>-->
{{error}}
{% endif %}
{% endblock %}

{% block css %}
<style>
* {
  box-sizing: border-box;
}

#myInput {
  background-image: url('/css/searchicon.png');
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
  font-size: 18px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 12px;
}

#myTable tr {
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>
{% endblock %}

{% block main %}
<div class="container">
    <p><h1>Requests:</h1></p>
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for requests.." title="Type in a name">
  <table class="table table-hover" id="myTable">
    <thead>
      <tr class="header">
        <th>User_Requested</th>
        <th>book_title</th>
          <th>Accept</th>
      </tr>
    </thead>
    <tbody>
{% for req_user,status,book_title,req_id in combine_list  %}
      <tr>
          <td>{{req_user}}</td>
        <td>{{book_title}}</td>
          <td><a href="{% url 'home:updatet' book_title req_id req_user username %}" >Accept</a> || <a href="{% url 'home:updatef' book_title req_id req_user username %}">Reject</a>
          </td>

      </tr>
{% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}



{% block js2 %}
<script>

function myFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
{% endblock %}